var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};
$jscomp.getConstructImplementation=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=$jscomp.objectCreate(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||
e}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};var GameObject=function(a,b,c,d){this.x=a;this.y=b;this.dx=c;this.dy=d;this.radius=2};
GameObject.prototype.contains=function(a,b){return Math.abs(this.x-a)<=this.radius&&Math.abs(this.y-b)<=this.radius};GameObject.prototype.update=function(){this.x=(this.x+this.dx)%canvas.width;0>this.x&&(this.x+=canvas.width);this.y=(this.y+this.dy)%canvas.height;0>this.y&&(this.y+=canvas.height)};GameObject.prototype.draw=function(){context.fillStyle="white";context.shadowBlur=BLUR_AMOUNT;context.beginPath();context.arc(this.x,this.y,this.radius,0,2*Math.PI);context.fill()};
var Ship=function(a,b,c,d){GameObject.call(this,a,b,c,d);this.heading=0;this.lastFiring=Date.now();this.firingDelay=100;this.radius=15;this.alive=!1;this.maxBullets=4;this.maxVelocity=6;this.friction=.99;this.lastThrust=Date.now();this.thrustInterval=50;this.exhaust=new GameObject(a,b,0,0);this.exhaust.radius=5};$jscomp.inherits(Ship,GameObject);
Ship.prototype.update=function(){GameObject.prototype.update.call(this);this.dx=0<this.dx?Math.min(this.dx*this.friction,this.maxVelocity):Math.max(this.dx*this.friction,-this.maxVelocity);this.dy=0<this.dy?Math.min(this.dy*this.friction,this.maxVelocity):Math.max(this.dy*this.friction,-this.maxVelocity);if(this.alive&&keyMap.get(ARROW_UP)&&this.lastThrust+this.thrustInterval<Date.now()){this.lastThrust=Date.now();var a=this.x+Math.cos(toRadians(this.heading+180))*this.radius,b=this.y-Math.sin(toRadians(this.heading+
180))*this.radius;this.exhaust.x=a;this.exhaust.y=b;this.exhaust.draw()}};Ship.prototype.hyperSpace=function(){spawnExplosion(this.x,this.y);this.x=randomInRange(0,canvas.width);this.y=randomInRange(0,canvas.height)};
Ship.prototype.fire=function(){if(Date.now()-this.lastFiring>this.firingDelay){this.lastFiring=Date.now();var a=10*Math.cos(toRadians(this.heading))+this.dx,b=-10*Math.sin(toRadians(this.heading))+this.dy,c=this.x+Math.cos(toRadians(this.heading))*this.radius*2,d=this.y-Math.sin(toRadians(this.heading))*this.radius*2;a=new Bullet(c,d,a,b);bullets.push(a);bullets.length>this.maxBullets&&bullets.shift()}};
Ship.prototype.draw=function(){context.strokeStyle="white";context.shadowBlur=BLUR_AMOUNT;context.beginPath();var a=Math.sqrt(Math.pow(this.radius,2)+Math.pow(this.radius,2)),b=this.radius*Math.cos(toRadians(this.heading)),c=this.radius*Math.sin(toRadians(this.heading)),d=a*Math.cos(toRadians(35-this.heading)),e=a*Math.sin(toRadians(35-this.heading)),f=a*Math.cos(toRadians(35+this.heading)),g=a*Math.sin(toRadians(35+this.heading)),h=(a-10)*Math.cos(toRadians(10-this.heading)),k=(a-10)*Math.sin(toRadians(10-
this.heading)),l=(a-10)*Math.cos(toRadians(10+this.heading));a=(a-10)*Math.sin(toRadians(10+this.heading));context.moveTo(this.x+b,this.y-c);context.lineTo(this.x-f,this.y+g);context.lineTo(this.x-l,this.y+a);context.lineTo(this.x-h,this.y-k);context.lineTo(this.x-d,this.y-e);context.lineTo(this.x+b,this.y-c);context.stroke()};Ship.prototype.kill=function(){this.alive=!1;bullets=[];spawnExplosion(this.x,this.y);removeLife()&&setTimeout(spawnPlayer,3E3)};
var Saucer=function(a,b,c,d){GameObject.call(this,a,b,c,d);this.maxSpeed=1;this.alive=!1;this.lastUpdate=Date.now();this.updateInterval=2E3;this.lastFiring=Date.now();this.firingInterval=3E3;this.bullets=[];this.maxBullets=4};$jscomp.inherits(Saucer,GameObject);
Saucer.prototype.update=function(){GameObject.prototype.update.call(this);this.lastUpdate+this.updateInterval<Date.now()&&(this.lastUpdate=Date.now(),this.dy=randomIntInRange(-this.maxSpeed,this.maxSpeed));this.lastFiring+this.firingInterval<Date.now()&&(this.lastFiring=Date.now(),this.fire());player.alive&&player.contains(this.x,this.y)&&player.kill();updateObjectArray(this.bullets)};
Saucer.prototype.kill=function(){this.alive=!1;this.bullets=[];score+=this.points;scoreInterval+=this.points;spawnExplosion(this.x,this.y)};Saucer.prototype.contains=function(a,b){return Math.abs(this.x-a)<=this.horizontalRadius&&Math.abs(this.y-b)<=this.verticalRadius};Saucer.prototype.fire=function(a,b){var c=new Bullet(this.x+2*a,this.y+2*b,a,b);c.firedBySaucer=!0;this.bullets.push(c);this.bullets.length>this.maxBullets&&this.bullets.shift()};
Saucer.prototype.draw=function(){context.strokeStyle="white";context.shadowBlur=BLUR_AMOUNT;context.beginPath();context.moveTo(this.x-2*this.horizontalRadius/5,this.y-this.verticalRadius/2);context.lineTo(this.x+2*this.horizontalRadius/5,this.y-this.verticalRadius/2);context.moveTo(this.x-this.horizontalRadius/5,this.y-this.verticalRadius);context.lineTo(this.x+this.horizontalRadius/5,this.y-this.verticalRadius);context.moveTo(this.x-2*this.horizontalRadius/5,this.y-this.verticalRadius/2);context.lineTo(this.x-
this.horizontalRadius/5,this.y-this.verticalRadius);context.moveTo(this.x+2*this.horizontalRadius/5,this.y-this.verticalRadius/2);context.lineTo(this.x+this.horizontalRadius/5,this.y-this.verticalRadius);context.moveTo(this.x-this.horizontalRadius,this.y);context.lineTo(this.x+this.horizontalRadius,this.y);context.moveTo(this.x-this.horizontalRadius,this.y);context.lineTo(this.x-2*this.horizontalRadius/5,this.y-this.verticalRadius/2);context.moveTo(this.x+this.horizontalRadius,this.y);context.lineTo(this.x+
2*this.horizontalRadius/5,this.y-this.verticalRadius/2);context.moveTo(this.x-this.horizontalRadius+this.horizontalRadius/5,this.y+this.verticalRadius/2);context.lineTo(this.x+this.horizontalRadius-this.horizontalRadius/5,this.y+this.verticalRadius/2);context.moveTo(this.x-this.horizontalRadius+this.horizontalRadius/5,this.y+this.verticalRadius/2);context.lineTo(this.x-this.horizontalRadius,this.y);context.moveTo(this.x+this.horizontalRadius-this.horizontalRadius/5,this.y+this.verticalRadius/2);context.lineTo(this.x+
this.horizontalRadius,this.y);context.stroke()};var LargeSaucer=function(a,b,c,d){Saucer.call(this,a,b,c,d);this.points=200;this.verticalRadius=15;this.horizontalRadius=30};$jscomp.inherits(LargeSaucer,Saucer);LargeSaucer.prototype.fire=function(){var a=randomInRange(0,360);Saucer.prototype.fire.call(this,10*Math.cos(a)+this.dx,10*Math.sin(a)-this.dy)};var SmallSaucer=function(a,b,c,d){Saucer.call(this,a,b,c,d);this.points=1E3;this.verticalRadius=10;this.horizontalRadius=20};
$jscomp.inherits(SmallSaucer,Saucer);SmallSaucer.prototype.fire=function(){var a=randomInRange(.9,1.1);7E4<score&&(a=1);a*=Math.atan2(this.y-player.y,player.x-this.x);Saucer.prototype.fire.call(this,10*Math.cos(a)+this.dx,-10*Math.sin(a)+this.dy)};
var Explosion=function(a,b,c,d){Saucer.call(this,a,b,0,0);this.startTime=Date.now();this.explosionTimer=c;this.debrisCount=d;this.radius=1;this.debris=[];for(a=0;a<this.debrisCount;a++)b=new GameObject(this.x,this.y,randomInRange(-.5,.5),randomInRange(-.5,.5)),this.debris.push(b)};$jscomp.inherits(Explosion,Saucer);Explosion.prototype.update=function(){return this.startTime+this.explosionTimer<Date.now()};Explosion.prototype.draw=function(){updateObjectArray(this.debris)};
var Bullet=function(a,b,c,d){GameObject.call(this,a,b,c,d);this.radius=3;this.firedBySaucer=!1};$jscomp.inherits(Bullet,GameObject);Bullet.prototype.update=function(){GameObject.prototype.update.call(this);for(var a=0;a<asteroids.length;a++){var b=asteroids[a];if(b.contains(this.x,this.y))return b.kill(),!0}return saucer.alive&&!this.firedBySaucer&&saucer.contains(this.x,this.y)?(saucer.kill(),!0):player.alive&&player.contains(this.x,this.y)?(player.kill(),!0):!1};
var Asteroid=function(a,b,c,d){GameObject.call(this,a,b,c,d);this.shape=randomIntInRange(0,2);this.points=[];this.alive=!0;this.maxSpeed=3};$jscomp.inherits(Asteroid,GameObject);Asteroid.prototype.update=function(){GameObject.prototype.update.call(this);player.alive&&this.contains(player.x,player.y)&&player.kill();return!this.alive};Asteroid.prototype.kill=function(){this.alive=!1;timeLastDestroyed=Date.now();score+=this.points;scoreInterval+=this.points;spawnExplosion(this.x,this.y)};
Asteroid.prototype.draw=function(){context.strokeStyle="white";context.shadowBlur=BLUR_AMOUNT;context.beginPath();0===this.shape?(context.moveTo(this.x-this.radius/4,this.y-this.radius),context.lineTo(this.x+this.radius/2,this.y-this.radius),context.lineTo(this.x+this.radius,this.y-this.radius/4),context.lineTo(this.x+this.radius,this.y+this.radius/2),context.lineTo(this.x,this.y+this.radius),context.lineTo(this.x,this.y+this.radius),context.lineTo(this.x,this.y+this.radius/20),context.lineTo(this.x-
this.radius/2,this.y+this.radius),context.lineTo(this.x-this.radius,this.y+this.radius/4),context.lineTo(this.x-this.radius/2,this.y),context.lineTo(this.x-this.radius,this.y-this.radius/4),context.lineTo(this.x-this.radius/2-this.radius/6,this.y-this.radius/2-this.radius/8),context.lineTo(this.x-this.radius/2,this.y-this.radius/2-this.radius/8),context.lineTo(this.x-this.radius/4,this.y-this.radius)):1===this.shape?(context.moveTo(this.x,this.y-this.radius/2),context.lineTo(this.x+this.radius/4,
this.y-this.radius),context.lineTo(this.x+this.radius,this.y-this.radius/2),context.lineTo(this.x+this.radius/2+this.radius/4,this.y),context.lineTo(this.x+this.radius,this.y+this.radius/2),context.lineTo(this.x+this.radius/4,this.y+this.radius),context.lineTo(this.x-this.radius/2,this.y+this.radius),context.lineTo(this.x-this.radius,this.y+this.radius/2),context.lineTo(this.x-this.radius,this.y-this.radius/2),context.lineTo(this.x-this.radius/2,this.y-this.radius),context.lineTo(this.x,this.y-this.radius/
2)):2===this.shape&&(context.moveTo(this.x-this.radius/2,this.y-this.radius),context.lineTo(this.x+this.radius/4,this.y-this.radius),context.lineTo(this.x+this.radius,this.y-this.radius/2),context.lineTo(this.x+this.radius,this.y-this.radius/4),context.lineTo(this.x+this.radius/4,this.y),context.lineTo(this.x+this.radius,this.y+this.radius/4),context.lineTo(this.x+this.radius/3,this.y+this.radius),context.lineTo(this.x+this.radius/10,this.y+this.radius/2+this.radius/4),context.lineTo(this.x-this.radius/
2,this.y+this.radius),context.lineTo(this.x-this.radius,this.y+this.radius/3),context.lineTo(this.x-this.radius,this.y-this.radius/3),context.lineTo(this.x-this.radius/2+this.radius/4,this.y-this.radius/3),context.lineTo(this.x-this.radius/2,this.y-this.radius));context.stroke()};var LargeAsteroid=function(a,b,c,d){Asteroid.call(this,a,b,c,d);this.radius=40;this.points=20};$jscomp.inherits(LargeAsteroid,Asteroid);
LargeAsteroid.prototype.kill=function(){Asteroid.prototype.kill.call(this);var a=new MediumAsteroid(this.x,this.y,randomInRange(-this.maxSpeed,this.maxSpeed),randomInRange(-this.maxSpeed,this.maxSpeed)),b=new MediumAsteroid(this.x,this.y,randomInRange(-this.maxSpeed,this.maxSpeed),randomInRange(-this.maxSpeed,this.maxSpeed));asteroids.push(a);asteroids.push(b)};var MediumAsteroid=function(a,b,c,d){Asteroid.call(this,a,b,c,d);this.radius=20;this.points=50};$jscomp.inherits(MediumAsteroid,Asteroid);
MediumAsteroid.prototype.kill=function(){Asteroid.prototype.kill.call(this);var a=new SmallAsteroid(this.x,this.y,randomInRange(-this.maxSpeed,this.maxSpeed),randomInRange(-this.maxSpeed,this.maxSpeed)),b=new SmallAsteroid(this.x,this.y,randomInRange(-this.maxSpeed,this.maxSpeed),randomInRange(-this.maxSpeed,this.maxSpeed));asteroids.push(a);asteroids.push(b)};var SmallAsteroid=function(a,b,c,d){Asteroid.call(this,a,b,c,d);this.radius=10;this.points=100};$jscomp.inherits(SmallAsteroid,Asteroid);
var GAME_SPEED=1E3/60,CANVAS_BORDER_COLOUR="white",CANVAS_BACKGROUND_COLOUR="rgba(0, 0, 0, 0.5)",BLUR_AMOUNT=5,canvas=document.getElementById("gameCanvas"),context=canvas.getContext("2d"),ARROW_LEFT="ArrowLeft",ARROW_RIGHT="ArrowRight",ARROW_UP="ArrowUp",SPACE="Space",KEY_H="KeyH",keyMap=new Map;keyMap.set(ARROW_LEFT,!1);keyMap.set(ARROW_RIGHT,!1);keyMap.set(ARROW_UP,!1);keyMap.set(SPACE,!1);keyMap.set(KEY_H,!1);
var gameMode="intro",lives=[],asteroids=[],bullets=[],explosions=[],score=0,scoreInterval=0,highScore=0,highScores=[],initials=["a",null,null],currentInitial=0,timeLastDestroyed=Date.now(),lastSaucer=Date.now(),saucerInterval=3E4,displayPlayer=!0,displayGameOver=!0,displayHighScores=!1,flashOn=!0,introModeTimer=null,pushStartTimer=null,saucer=new SmallSaucer(0,0,0,0);saucer.alive=!1;var player=null;configureWindow();loadHighScores();toIntro();spawnPlayer();player.alive=!1;main();
document.addEventListener("keydown",function(a){a.code===SPACE&&"intro"===gameMode?startGame():player.alive&&a.code===KEY_H?player.hyperSpace():"end"===gameMode?a.code===ARROW_LEFT?endScreenLeft():a.code===ARROW_RIGHT?endScreenRight():a.code===SPACE&&endScreenSpace():(a.code===SPACE&&!keyMap.get(a.code)&&player.alive&&player.fire(),keyMap.set(a.code,!0))});document.addEventListener("keyup",function(a){keyMap.set(a.code,!1)});window.addEventListener("resize",configureWindow,!1);
function main(){setTimeout(function(){clearCanvas();updateObjects();if("intro"===gameMode)if(drawIntroText(),score=0,displayHighScores)asteroids=[],explosions=[],saucer.alive=!1;else{for(;10>asteroids.length;)spawnAsteroids(1);saucer.alive||spawnSaucer()}else"game"===gameMode?(drawGameText(),handlePlayerInput(),0===asteroids.length&&timeLastDestroyed+4E3<Date.now()&&spawnAsteroids(),1E4<=scoreInterval&&(addLife(),scoreInterval%=1E4),!saucer.alive&&lastSaucer+saucerInterval<Date.now()&&(lastSaucer=
Date.now(),spawnSaucer())):"end"===gameMode&&drawEndText();main()},GAME_SPEED)}function updateObjects(){updateObjectArray(explosions);updateObjectArray(asteroids);updateObjectArray(bullets);saucer.alive&&(saucer.update(),saucer.draw());"game"===gameMode&&player.alive&&(player.update(),player.draw())}function updateObjectArray(a){for(var b=0;b<a.length;b++){var c=a[b];c.draw();c.update()&&(a.splice(b,1),b=Math.max(b-1,0))}}
function spawnPlayer(){for(var a=!0,b=0;b<asteroids.length;b++)if(asteroids[b].contains(canvas.width/2,canvas.height/2)){a=!1;break}saucer.alive&&saucer.contains(canvas.width/2,canvas.height/2)&&(a=!1);a?(player=new Ship(canvas.width/2,canvas.height/2,0,0),player.alive=!0):setTimeout(spawnPlayer,1E3)}function spawnExplosion(a,b,c,d){a=new Explosion(a,b,void 0===c?1500:c,void 0===d?10:d);explosions.push(a)}
function spawnSaucer(){saucer=4E4<=score||0===randomIntInRange(0,1)?new SmallSaucer(0,randomIntInRange(0,canvas.height),-saucer.maxSpeed,saucer.maxSpeed):new LargeSaucer(0,randomIntInRange(0,canvas.height),-saucer.maxSpeed,saucer.maxSpeed);saucer.alive=!0}
function spawnAsteroids(){for(var a=randomIntInRange(4,6),b=0;b<a;b++){var c=randomIntInRange(0,3);0===c?(c=new LargeAsteroid(0,randomInRange(0,canvas.height),randomInRange(-2,2),randomInRange(-2,2)),asteroids.push(c)):1===c?(c=new LargeAsteroid(randomInRange(0,canvas.width),0,randomInRange(-2,2),randomInRange(-2,2)),asteroids.push(c)):2===c?(c=new LargeAsteroid(canvas.width,randomInRange(0,canvas.height),randomInRange(-2,2),randomInRange(-2,2)),asteroids.push(c)):3===c&&(c=new LargeAsteroid(randomInRange(0,
canvas.width),canvas.height,randomInRange(-2,2),randomInRange(-2,2)),asteroids.push(c))}}function toIntro(){gameMode="intro";displayHighScores=!1;introModeTimer=setInterval(function(){displayHighScores=!displayHighScores},17E3);flashOn=!0;pushStartTimer=setInterval(function(){flashOn=!flashOn},500)}
function startGame(){score=0;asteroids=[];bullets=[];for(var a=0;3>a;a++)addLife();saucer.alive=!1;displayPlayer=!0;gameMode="game";spawnPlayer();clearInterval(introModeTimer);clearInterval(pushStartTimer);setTimeout(function(){displayPlayer=!1},3E3)}function endGame(){gameMode="end";setTimeout(function(){displayGameOver=!1},3E3)}function addLife(){var a=new Ship(30*(1+lives.length),60,0,0);a.heading=90;lives.push(a)}function removeLife(){lives.pop();return 0===lives.length?(endGame(),!1):!0}
function handlePlayerInput(){player.alive&&(keyMap.get(ARROW_LEFT)&&(player.heading=(player.heading+5)%360),keyMap.get(ARROW_RIGHT)&&(player.heading=(player.heading-5)%360),keyMap.get(ARROW_UP)&&(player.dx+=.1*Math.cos(toRadians(player.heading)),player.dy-=.1*Math.sin(toRadians(player.heading))))}
function clearCanvas(){context.shadowBlur=0;context.fillStyle=CANVAS_BACKGROUND_COLOUR;context.strokestyle=CANVAS_BORDER_COLOUR;context.fillRect(0,0,canvas.width,canvas.height);context.strokeRect(0,0,canvas.width-1,canvas.height-1)}
function drawIntroText(){drawScores();drawCoins();context.strokeStyle="white";context.shadowBlur=BLUR_AMOUNT;context.font="30px hyperspace";context.textAlign="center";flashOn&&context.strokeText("push start",canvas.width/2,canvas.height/5);context.strokeText("1 coin 1 start",canvas.width/2,9*canvas.height/10);if(displayHighScores){context.strokeText("high scores",canvas.width/2,2*canvas.height/7);context.textAlign="center";for(var a=0;a<highScores.length;a++)context.strokeText((a+1).toString()+". "+
highScores[a].score+" "+highScores[a].name,canvas.width/2,canvas.height/3+30*(a+1))}}function drawGameText(){drawScores();displayPlayer&&(context.strokeStyle="white",context.shadowBlur=BLUR_AMOUNT,context.font="30px hyperspace",context.textAlign="center",context.strokeText("player 1",canvas.width/2,canvas.height/5));for(var a=0;a<lives.length;a++)lives[a].draw()}
function drawEndText(){drawScores();drawCoins();context.strokeStyle="white";context.shadowBlur=BLUR_AMOUNT;context.font="30px hyperspace";if(displayGameOver)context.textAlign="center",context.strokeText("game over",canvas.width/2,canvas.height/5);else if(isHighScore()){asteroids=[];bullets=[];saucer.alive=!1;context.textAlign="left";var a=-context.measureText("your score is one of the ten best\n").width/2;context.strokeText("your score is one of the ten best\n",canvas.width/2+a,canvas.height/4);context.strokeText("please enter your initials\n",
canvas.width/2+a,canvas.height/4+30);context.strokeText("push rotate to select letter",canvas.width/2+a,canvas.height/4+60);context.strokeText("push fire when letter is correct",canvas.width/2+a,canvas.height/4+90);context.font="50px hyperspace";context.textAlign="center";a="";for(var b=0;b<initials.length;b++)a=null!=initials[b]?a+initials[b]:a+"_";context.strokeText(a,canvas.width/2,2*canvas.height/3)}else toIntro()}
function endScreenLeft(){null==initials[currentInitial]&&(initials[currentInitial]="a");var a=initials[currentInitial].charCodeAt(0)%97-1;a=0>a?String.fromCharCode(122):String.fromCharCode(97+a);initials[currentInitial]=a}function endScreenRight(){null==initials[currentInitial]&&(initials[currentInitial]="a");initials[currentInitial]=String.fromCharCode((initials[currentInitial].charCodeAt(0)%97+1)%26+97)}
function endScreenSpace(){null!=initials[currentInitial]&&(currentInitial++,3===currentInitial&&(addHighScore(),toIntro(),displayHighScores=!0))}function drawScores(){context.strokeStyle="white";context.shadowBlur=BLUR_AMOUNT;context.font="30px hyperspace";context.textAlign="left";context.strokeText(padInteger(score),10,30);context.font="20px hyperspace";context.textAlign="center";context.strokeText(padInteger(highScore),canvas.width/2,20)}
function drawCoins(){context.font="30px hyperspace";context.textAlign="right";context.strokeText("00",canvas.width-10,30)}function loadHighScores(){highScores=JSON.parse(localStorage.getItem("highScores")||"[]");null!=highScores[0]&&(highScore=highScores[0].score)}function saveHighScores(){localStorage.setItem("highScores",JSON.stringify(highScores))}function isHighScore(){if(10>highScores.length)return!0;for(var a=0;a<highScores.length;a++)if(highScores[a].score<score)return!0;return!1}
function addHighScore(){highScores.push({score:score,name:initials[0]+initials[1]+initials[2]});highScores.sort(function(a,b){return a.score<b.score?1:b.score<a.score?-1:0});10<highScores.length&&highScores.pop();saveHighScores();initials=["a",null,null];currentInitial=0}function padInteger(a){return 1===a.toString().length?"0"+a.toString():a.toString()}function randomInRange(a,b){return Math.random()*(b-a)+a}
function randomIntInRange(a,b){a=Math.ceil(a);b=Math.floor(b);return Math.floor(Math.random()*(b-a+1))+a}function toRadians(a){return Math.PI/180*a}
function configureWindow(){canvas.width=1366;canvas.height=768;canvas.style.width=window.innerWidth+"px";canvas.style.height=window.innerHeight+"px";context.shadowColor="white";context.shadowOffsetX=0;context.shadowOffsetY=0;context.lineWidth=2;context.shadowBlur=0;context.fillStyle="black";context.strokestyle="white";context.fillRect(0,0,canvas.width,canvas.height);context.strokeRect(0,0,canvas.width-1,canvas.height-1)};